name: Release
on: [push]

permissions: write-all

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code
    
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build and Push Image
        with:
          image: att-fiber-prom-exporter
          registry: ghcr.io
          dockerfile: Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

